name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: carvalhal/WebGoat
          cx_tenant: cx_seg
          base_uri: https://eu.ast.checkmarx.net/
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --debug --report-format sarif # \
            #--output-name ${{ steps.get-repo.outputs.repo }}
#      - name: Upload XML Artifact
      
      - name: Upload Checkmarx SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif #${{ steps.get-repo.outputs.repo }}.sarif
#        with:
#          name: cx_result.sarif
#          path: cx_result.sarif
